spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: currency-exchange-service
          uri: lb://CURRENCY-EXCHANGE-SERVICE
          predicates:
            - Path=/currency-exchange/**
        - id: currency-conversion-service
          uri: lb://CURRENCY-CONVERSION-SERVICE
          predicates:
            - Path=/currency-converter-feign/**
server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
